#######################################################################
#                          MCTennis                                   #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  mctennis:
    aliases:
      - "tennis"
  mctennisscoreboard:
    aliases:
      - "tennisscoreboard"

############################
# Scoreboard
# All global scoreboard settings.
############################
scoreboard:
  # How often are the permissions of a player checked to determine if he has got access to any scoreboard.
  checkForChangeChangeSeconds: 3
  # When a new player joins the server, after how many seconds are the scoreboards created.
  joinDelaySeconds: 3
