name: MCTennis
version: 1.9.0
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.mctennis.MCTennisPlugin
softdepend: [ PlaceholderAPI, Geyser-Spigot ]
api-version: 1.13
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.17.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.17.0
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.3.0
  - com.fasterxml.jackson.core:jackson-databind:2.3.0
  - com.google.inject:guice:7.0.0
  - com.google.code.gson:gson:2.10.1
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - aopalliance:aopalliance:1.0
